environment:
  matrix:
    - nodejs_version: "8.4.0"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

branches:
  only:
  - v2
build_script:
- cmd: tsc

# test_script:
#   - node --version
#   - npm --version
#   - npm run test-ci
version: "{build}"